name: Java CI with Maven

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    # Step 1: Compilazione [cite: 67]
    - name: Compile Project
      run: mvn compile

    # Step 2: Esecuzione Test [cite: 68]
    - name: Run Tests
      run: mvn test

    # Step 3: Analisi Statica (Checkstyle) [cite: 69]
    # Eseguita in fase di package come richiesto [cite: 69]
    - name: Static Code Analysis
      run: mvn checkstyle:check

    #Coveralls
    - name: Run Tests with Coverage
      run: mvn clean test jacoco:report

    - name: Upload coverage to Coveralls
      uses: coverallsapp/github-action@v2
      with:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      file: target/site/jacoco/jacoco.xml